### ISSUE TITLE
关于授权问题

### ISSUE THREAD

**Issue by Linux-qitong** [KeqingMoe/sakurairo#1]
我看了一下，原来项目是gpl2协议，你也用gpl2协议就好，不需要授权，遵守gpl2开源协议即可

**Comment by KeqingMoe** [comment]
好的，感谢您提出的 Issue。不过，我还有一些疑问：
我所说的授权指的是使用了和原主题相同的名字，模仿原主题的样式，以及一些原主题的公共资源（例如一些图标），这是我所担心的可能构成侵权的问题；在源代码方面，而我并没有直接复制、引用、修改原主题的代码，我是否必须使用 GPL2 呢？

**Comment by Linux-qitong** [comment]
是的，必须使用gpl2协议，因为你这是衍生的

**Comment by Linux-qitong** [comment]
我推荐增加个演示站点，这样可以让大家看到成果

**Comment by KeqingMoe** [comment]
好的，感谢您的解答。
关于演示站点，因为当时仅仅只做完了首页，因为要开学了就先提交了，于是还没放出来。这几天一直东奔西跑在忙，今天终于有空了，刚好在添加新内容，应该很快就能做好展示文章的页面，届时我会放出演示站点。

**Comment by KeqingMoe** [comment]
已使用 GPL2 协议，并部署到了演示站点。
